services:
  - type: web
    name: prefiction-web
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    autoDeploy: true
